1st Milestone, Calculator Project - REACT
AnthonyTC89/react_calculator pull request #1
Opened 2020-01-03 21:21 UTC by AnthonyTC89

Hello!, this is the basic setup with 'create-react-app' and deploy it in Heroku.

2020-01-06 06:46 UTC, bolah2009 requested changes
Hi @AnthonyTC89 

Good setup! 👏🏾

#### 1. Let's setup linter, [see here for instructions](https://github.com/microverseinc/linters-config/tree/master/react-redux)
   ![image](https://user-images.githubusercontent.com/36057474/71800210-c3979280-3057-11ea-9eb0-2feb1e57f665.png)
#### 2.  Delete unnecessary files generated by CRA.
   ![image](https://user-images.githubusercontent.com/36057474/71800257-de6a0700-3057-11ea-8222-3bbaf68eb10a.png)




#### :recycle:  Make these changes and submit another code review request. 👍🏾

#### Feel free to reach me on slack if you having issues implementing these features. :relaxed: 

Good luck with your next submission. :star2: 

Cheers
[Bola](https://bolabuari.com/)

###### PS: Note that comments tagged as `OPTIONAL` are not part of the minimum requirements to approve this PR

2020-01-06 06:46 UTC, bolah2009 commented on src/serviceWorker.js
> +// This optional code is used to register a service worker.
You can delete this file unless you want to use it to make the app a PWA.

2020-01-06 06:46 UTC, bolah2009 commented on src/App.test.js
> +import React from 'react';
We could delete this too unless we planning to test the app.

2020-01-06 15:50 UTC, AnthonyTC89 commented
All the necessary changes were done. Thank you for the annotations.

2020-01-06 19:04 UTC, jofer86 requested changes
## 👋 👋 Hello I will be conducting the follow-up review for this milestone.

- There are a some issues with your linting configuration as they are stated below, please see to tend to them, as they are quite code-breaking errors that need attention. Please tend to them and do ask for another code review.

2020-01-06 19:04 UTC, jofer86 commented on eslint.config
> +}
This file is not necessary as it should be the .eslintrc.json who should be taking care of the eslint configuration.

2020-01-06 19:04 UTC, jofer86 commented on .stickler.yml
> +      - '.eslintrc.js'
This file also differs from the indicated in the Microverse instructions, it should look like [this one over here](https://github.com/microverseinc/linters-config/blob/master/react-redux/.stickler.yml) 
![image](https://user-images.githubusercontent.com/46115725/71840149-577e5400-3082-11ea-9e60-cdaf05b3c94b.png) 
, also your stickler file is ignoring your config file which is the same as running no linter at all since it won't show any errors in the stickler check. That is not cool it's like setting up a linter that will always pass no matter what, please do remove the ignore line as it will be pointless to have a linter with the config file ignored.

This might have been caused because you have two eslint config files. So stickler is ignoring one by default.  Please pay close attention to that as it might be misinterpreted.

2020-01-06 19:04 UTC, jofer86 commented on .eslintrc.js
> +};
We need to make sure we follow the Linter setup instructions stated [in this link right here](https://github.com/microverseinc/linters-config/tree/master/react-redux) there are a couple of things that differ from the initial instructions, such as the format, and some of the configurations inside the config file lets keep it as to the manual as possible, in case there are any rules that need to be changed in order for your app to run properly, please do explain in detail in future PRs.

2020-01-06 19:04 UTC, jofer86 commented on src/App.js
> +        <img src={logo} className="App-logo" alt="logo" />
This line along with the logo file are not necesary, please do delete the line and the file in your app. Lets leave an empty div here so that you can start from scratch.

2020-01-06 19:04 UTC, jofer86 commented on src/App.css
> +}
This CSS is generated by CRA, please do remove.

2020-01-06 19:04 UTC, jofer86 commented on src/logo.svg
> +</svg>
This SVG should be removed as it was generated by CRA

2020-01-07 15:42 UTC, shloch approved these changes
## Hello @AnthonyTC89 
### You get a thumbs up from me 👍👍
### You can merge this, see you on next milestone 🏊🏊🏊🏊

2020-01-07 17:42 UTC, merged